const images = {}

const icons = {
  chevron_down: require('./icons/Chevron/Down.png'),
  chevron_up: require('./icons/Chevron/Up.png'),
  chevron_left: require('./icons/Chevron/Left.png'),
  chevron_right: require('./icons/Chevron/Right.png'),

  radio_button_active: require('./icons/RadioButton/Active.png'),
  radio_button_inactive: require('./icons/RadioButton/Inactive.png'),

  barcode: require('./icons/Barcode.png'),
  bell: require('./icons/Bell.png'),
  below: require('./icons/Below.png'),
  bill: require('./icons/Bill.png'),
  blockchain_technology: require('./icons/Blockchain_technology.png'),
  box_important: require('./icons/Box_important.png'),
  calendar: require('./icons/Calendar.png'),
  calendar_1: require('./icons/Calendar-1.png'),
  camera: require('./icons/Camera.png'),
  chart: require('./icons/Chart.png'),
  chat: require('./icons/Chat.png'),
  checked_checkbox: require('./icons/Checked_checkbox.png'),
  circled_menu: require('./icons/Circled_menu.png'),
  clear_symbol: require('./icons/Clear_symbol.png'),
  close: require('./icons/Close.png'),
  commercial: require('./icons/Commercial.png'),
  conflict: require('./icons/conflict.png'),
  contact_us: require('./icons/Contact_us.png'),
  credit_card: require('./icons/Credit_card.png'),
  data_transfer: require('./icons/Data_transfer.png'),
  discount: require('./icons/Discount.png'),
  email: require('./icons/Email.png'),
  estimate: require('./icons/Estimate.png'),
  export: require('./icons/Export.png'),
  eye_hide: require('./icons/Eye-Hide.png'),
  eye_show: require('./icons/Eye-Show.png'),
  filter: require('./icons/Filter.png'),
  flash: require('./icons/Flash.png'),
  food_drink: require('./icons/Food_Drink.png'),
  gallery: require('./icons/Gallery.png'),
  help: require('./icons/Help.png'),
  home: require('./icons/Home.png'),
  image: require('./icons/Image.png'),
  ireasure_chest: require('./icons/Ireasure_chest.png'),
  left: require('./icons/Left.png'),
  lock: require('./icons/Lock.png'),
  love: require('./icons/Love.png'),
  menu: require('./icons/Menu.png'),
  message: require('./icons/Message.png'),
  note: require('./icons/Note.png'),
  ok: require('./icons/Ok.png'),
  phonelink_rin: require('./icons/Phonelink_ring.png'),
  plus: require('./icons/Plus.png'),
  plus_1: require('./icons/Plus-1.png'),
  privacy: require('./icons/Privacy.png'),
  scan_stock: require('./icons/Scan_stock.png'),
  search: require('./icons/Search.png'),
  send: require('./icons/Send.png'),
  settings: require('./icons/Setting.png'),
  shop: require('./icons/Shop.png'),
  terms_and_conditions: require('./icons/Terms_and_conditions.png'),
  upward: require('./icons/Upward.png'),
  unchecked_checkbox: require('./icons/unchecked_checkbox.png'),
  user: require('./icons/User.png'),
  whatsapp: require('./icons/Whatsapp.png')
}

export { images, icons }
